//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吓到我们的新谷歌翻译，学者却这样评价它2016-10-2 6:56    雷锋网责编：远洋本周三，谷歌发布新版神经机器翻译（GNMT）系统，并表示使用了最先进的训练技术，翻译质量会有较大提升。虽然谷歌一直都在将神经网络技术用于自己的人工智能产品，但好像自Alphago以后，“神经”二字特别敏感，新的翻译系统也引起了不少争论。现在流传比较广的评价来自从事翻译职业的网友：作为翻译，看到这个新闻的时候，我理解了18世纪纺织工人看到蒸汽机时的忧虑与恐惧。这种兼具历史感与行业认知的评价特别感染人。不过凡事要客观看待，雷锋网亲测后发现，翻译质量比传统的机翻体验好上不少，但仍不到实用的地步。如果你想知道“如何评价”这件事，或许可以看看加拿大国家研究委员会NRC多语言处理研究组陈博兴研究员的点评。他1998年本科毕业于北京大学，2003年博士毕业于中国科学院声学研究所，主要研究兴趣是自然语言处理、机器翻译和机器学习。以下是点评内容：这两天，“受邀”在几个微信群里点评刷遍微博和微信朋友圈的关于谷歌神经网络机器翻译的文章和报道。我的点评如下：首先，谷歌所做的事情是将这两年学术界神经网络机器翻译的多种最新技术做了一个整合集成，利用 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testString {
            get {
                return ResourceManager.GetString("testString", resourceCulture);
            }
        }
    }
}
